### ISSUE TITLE
please pin this repo

### ISSUE THREAD

**Issue by xieyuheng** [OrgTangle/discussion#1]

**Comment by kaushalmodi** [comment]
I pinned this repo, but how does that help? Now it hides all the other repos from the front page of this org.

**Comment by xieyuheng** [comment]
Thanks.

It does not hide other repos, it just highlights itself.

**Comment by xieyuheng** [comment]
I am looking toward this https://github.com/forthhub
which is also a collection-like org-mode

**Comment by kaushalmodi** [comment]
At least on phone it now looks like this:

https://www.dropbox.com/s/6zt7nkk20ijfrpa/Screenshot_20181004-211713.png?dl=0

Earlier all the repos were visible there. 

May be we pin the discussion repo after the total number of repos exceeds 6?

**Comment by xieyuheng** [comment]
ok!

**Comment by kaushalmodi** [comment]
Alright, I have unpinned it for now. Now all 4 repos show up on the org front page on both phone and desktop.
