### ISSUE TITLE
please add a whatever picture as logo for now

### ISSUE THREAD

**Issue by xieyuheng** [OrgTangle/discussion#2]

**Comment by kaushalmodi** [comment]
Do you have a good suggestion?

**Comment by xieyuheng** [comment]
https://www.google.com/imgres?imgurl=https%3A%2F%2Fpreviews.123rf.com%2Fimages%2Fnatalypaint%2Fnatalypaint1604%2Fnatalypaint160400054%2F54942926-zen-doodle-or-zen-tangle-floral-pattern-composition-in-style-mehndi-illustration.jpg&imgrefurl=https%3A%2F%2Fwww.123rf.com%2Fphoto_54942926_stock-illustration-zen-doodle-or-zen-tangle-floral-pattern-composition-in-style-mehndi-illustration.html&docid=R4eFDUPQ0oZS3M&tbnid=B6MocOPPFVvYRM%3A&vet=10ahUKEwinleuIje7dAhVrwFQKHZopDU0QMwi3AShZMFk..i&w=1300&h=1300&client=firefox-b-ab&bih=576&biw=1120&q=tangle&ved=0ahUKEwinleuIje7dAhVrwFQKHZopDU0QMwi3AShZMFk&iact=mrc&uact=8

https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic1.squarespace.com%2Fstatic%2F5a8b7d2c010027b3a111f50c%2F5adbd4971ae6cfdcd74230d6%2F5af8cd4a575d1f0767106380%2F1526759502075%2Ftangle%25239_crop_16%25281920%2529.jpg&imgrefurl=https%3A%2F%2Fwww.lauravandenburgh.art%2Ftangle-drawings-1%2F&docid=uJ0OoQeDXmbu2M&tbnid=bm-ot7I6Egdn5M%3A&vet=12ahUKEwjg6M2Pje7dAhVnzVQKHS8DDac4ZBAzKCUwJXoECAEQJg..i&w=1000&h=841&client=firefox-b-ab&bih=576&biw=1120&q=tangle&ved=2ahUKEwjg6M2Pje7dAhVnzVQKHS8DDac4ZBAzKCUwJXoECAEQJg&iact=mrc&uact=8

https://www.google.com/imgres?imgurl=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1002098649197932544%2FJc5hglm3_400x400.jpg&imgrefurl=https%3A%2F%2Ftwitter.com%2Ftrimtangle&docid=pXiP4qtFEgOS3M&tbnid=mLLkKGt8VldAsM%3A&vet=12ahUKEwjg6M2Pje7dAhVnzVQKHS8DDac4ZBAzKCYwJnoECAEQJw..i&w=400&h=400&client=firefox-b-ab&bih=576&biw=1120&q=tangle&ved=2ahUKEwjg6M2Pje7dAhVnzVQKHS8DDac4ZBAzKCYwJnoECAEQJw&iact=mrc&uact=8

https://www.google.com/imgres?imgurl=https%3A%2F%2Fcraftwhack.com%2Fwp-content%2Fuploads%2F2015%2F07%2Fbullseyezentangle.jpg&imgrefurl=https%3A%2F%2Fcraftwhack.com%2Fhow-to-make-a-cool-bullseye-tangle-drawing%2F&docid=9kqNw5CBGJfynM&tbnid=xRqVY8LopUc21M%3A&vet=12ahUKEwjg6M2Pje7dAhVnzVQKHS8DDac4ZBAzKDAwMHoECAEQMg..i&w=800&h=805&client=firefox-b-ab&bih=576&biw=1120&q=tangle&ved=2ahUKEwjg6M2Pje7dAhVnzVQKHS8DDac4ZBAzKDAwMHoECAEQMg&iact=mrc&uact=8

**Comment by xieyuheng** [comment]
sorry about the long urls ...

**Comment by xieyuheng** [comment]
I can do this, if I can change setting.

**Comment by kaushalmodi** [comment]
I've added the image. 

**Credit**: *Jeanette Nyberg* - https://craftwhack.com/how-to-make-a-cool-bullseye-tangle-drawing/
