### ISSUE TITLE
Comparison of tangling system implementations

### ISSUE THREAD

**Issue by PaulBatchelor** [OrgTangle/discussion#4]
I think it would be helpful to build a table that does a comparison of the various tangling systems.

For starters, here are some things we could look at:

- Language
- License
- Support NoWeb code expansion
- Support for Code block header parsing

Thoughts?

**Comment by kaushalmodi** [comment]
Sure. I have broken down the Org Tangle support best to my knowledge in this Features todo list: https://github.com/OrgTangle/ntangle#features

Those can be made rows of the table (Org table). Let's create a comparison.org file in this repo and I can later move it to a landing website ( https://github.com/OrgTangle/discussion/issues/3 ) for OrgTangle.

**Comment by xieyuheng** [comment]
a wiki would be nice

**Comment by xieyuheng** [comment]
https://github.com/OrgTangle/discussion/wiki/Comparison-of-Tangling-Systems

**Comment by xieyuheng** [comment]
feature-list itself can be a wiki page

also org spec efforts can have a page

page page page ...

**Comment by xieyuheng** [comment]
wiki support of github is not perfect.

but we can use it for now.

(I also want to build new simple wiki engine which support org-mode and marddown)

**Comment by PaulBatchelor** [comment]
I've never used the GH wiki page before, so I'm having a little trouble adding content.
I tried cloning and pushing (to master), but it says I don't have access? Am I missing something?

Alternatively, someone could add the following entries for me:

Name: Worgle

Language: C

License: Public Domain

NoWeb: Yes

Code Block (not sure what you mean by this?):  Multi-file output via ":tangle"

**Comment by xieyuheng** [comment]
clone it by
`git clone https://github.com/OrgTangle/discussion.wiki.git`
the repo would be called `discussion.wiki`
in the repo you can change `.git/config` to
```
url = git@github.com:OrgTangle/discussion.wiki.git
```
to use git protocol instead of https

**Comment by xieyuheng** [comment]
a page is just an org-mode file, rendered to html

**Comment by xieyuheng** [comment]
deleting the `Code Block` section for now it is a bit not clear

**Comment by xieyuheng** [comment]
I did it for you :)

hope next time you can edit it too

**Comment by PaulBatchelor** [comment]
Thanks!
