### ISSUE TITLE
Can't add topics or website to Worgle Repo

### ISSUE THREAD

**Issue by PaulBatchelor** [OrgTangle/discussion#5]
For some reason, I am unable to add things like topics and website to the Worgle page. If I fork the repo to my own account, I am able to add these things. This smells like a permissions problem, but I am unsure.

Can anyone help with this?

**Comment by kaushalmodi** [comment]
> Can anyone help with this?

Looking into this now. I haven't touched admin of any repo other than this "discussion" repo (to give all us OrgTanglers write access to it) and mine.

**Comment by kaushalmodi** [comment]
@PaulBatchelor You are now the Admin of Worgle repo as you should be. I don't know how you had only Write access (I'll ensure that the original dev retains the Admin access next time anyone adds their repo).

Thanks for bringing this to attention.

**Comment by PaulBatchelor** [comment]
woo! Thanks for the fast response.

**Comment by kaushalmodi** [comment]
Interestingly @xieyuheng is already Admin of org-rs repo without any intervention from my side. May be you picked the wrong permissions where importing it here?

**Comment by kaushalmodi** [comment]
ok, @thblt also had Write-only (and not Admin) on his repo too. I've fixed that too. I'll keep an eye on these for future repos.
